export const POST_COLLAPSED_DATA_STARTED = "POST_COLLAPSED_DATA_STARTED"
export const POST_COLLAPSED_DATA_FAILED = "POST_COLLAPSED_DATA_FAILED"
export const POST_COLLAPSED_DATA_SUCCESS = "POST_COLLAPSED_DATA_SUCCESS"